# Generated by Django 5.2 on 2025-05-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rhithm', '0002_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='confirm_password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
